### ISSUE TITLE
BPS Patch

### ISSUE THREAD

**Issue by Krokodyl** [Dom-aka-Doke/Advanced-SNES-ROM-Utility#2]
Hello,

I found your tool on romhacking.net and I really think it's great. It's nice to see people working on useful tools for the community.
I've worked on a rom translation from Japanese to English. (https://github.com/Krokodyl/dokapon-english)
As part of the program (in Java) that I developed for this, I made a BPS patcher, following the official BPS specs.
In order to test the BPS file generated, I used Flips 1.31 and it works.
Now for the issue, when I try to apply the same patch using Advanced-SNES-ROM-Utility I get an error.
I uploaded the files there (https://github.com/Krokodyl/dokapon-english/tree/master/tools/advanced-snes-rom-utility) for you to test.

The problem could come from my patch generation, as my patch is bigger than the one Flips creates, even though both works.
It could also come from the fact that my patch extends the length of the rom (from 1536ko to 1760ko).
If it helps, my patcher in Java is there (https://github.com/Krokodyl/dokapon-english/tree/master/dokapon-gen/src/main/java/dokapon/bps)

Just letting you know.
Cheers

**Comment by Dom-aka-Doke** [comment]
Hello,

many thanks for submitting and describing this issue!

Advanced-SNES-ROM-Utility is generally able to expand and truncate a ROM, if the target size varies from the source ROM.
I just took a quick look at it and it seems, that your patch uses metadata information. Even though I also follwed the official specs from Near, it seems like I just skipped this part. My bad... I will fix that and release a new version soon!

P.S.: Nice translation! Look like an interesting game. But you really should expand your ROM to full 16 MBit and fix the checksum.

Cheers

**Comment by Krokodyl** [comment]
I didn't even know that rom expansion was a thing. What is the benefit of doing that? Is it a better compatibility for emulators?

**Comment by Dom-aka-Doke** [comment]
Better compatibilty with some old emulators and it will be possible to create a physical copy, if you want to. Also I guess it belongs to a good practice doing it.

Anyway, I just fixed the issue and submitted a new version to RHDN, so I will close this issue now.

Thanks again for your submission and help to improve this tool!
