### ISSUE TITLE
manual into tooltips

### ISSUE THREAD

**Issue by jeffythedragonslayer** [Dom-aka-Doke/Advanced-SNES-ROM-Utility#9]
I suggest moving the information in the manual form into tooltips - currently nothing is displayed if you hover over most buttons

**Comment by Dom-aka-Doke** [comment]
Hi Jeff!
Thanks for submitting this issue.
I also had in mind doing this, but with a tooltip on hovering every button, this might annoy some people (including myself).
Most buttons are self-explanatory anyway (at least I hope so).

**Comment by jeffythedragonslayer** [comment]
I generally don't like tooltips that display instantly.  I was thinking there should be some sort of delay.

**Comment by Dom-aka-Doke** [comment]
Reworked manual, so tooltips aren't needed anymore.
Everything else should be self-explanatory, I guess.
